### ISSUE TITLE
Fixing bounds and getSafe() 

### ISSUE THREAD

**Issue by ronnie-dumesh** [BryanGraeser/fallen-flame#35]
Work from branch add-enemies

As discussed on call, changes need to be made to LevelModel to fix the Bounds. I think this will stop any crashing from occuring.

I also commented out the code in levelModel.initialize() that adds wheelObstacles and blockObstacles to making a tile unsafe. The functions setBoxObstacleInGrid() and setWheelObstacleInGrid() need to be fixed to prevent crashing. getSafe() also needs to be fixed to assure that a tile is inBounds and that there is no obstacle on it.

**Comment by BryanGraeser** [comment]
This is fixed in latest master version with exterior walls.
