### ISSUE TITLE
Weird movement

### ISSUE THREAD

**Issue by BryanGraeser** [BryanGraeser/fallen-flame#42]
I may be imagining this, but it looks like some sort of clipping issue?

**Comment by BryanGraeser** [comment]
This is the thing the TA mentioned.

**Comment by BryanGraeser** [comment]
So I think this is more an issue where the player randomly speeds up and slows down, looking into it

**Comment by foxhatleo** [comment]
It seems that I can't quite reproduce this issue.

**Comment by BryanGraeser** [comment]
The issue is we have the movement force and max speed, I think it should just be a constant speed in the direction the player is moving

**Comment by BryanGraeser** [comment]
SOLVED!! #116
