### ISSUE TITLE
AI does not switch to chasing flare if going to player last known position

### ISSUE THREAD

**Issue by BryanGraeser** [BryanGraeser/fallen-flame#59]
Not sure if this is desired behavior, but I think having the AI switch to chasing the flare makes more gameplay sense.

**Comment by ronnie-dumesh** [comment]
I would personally disagree. Imagine yourself as an enemy trying to chase down the player. The flare is of concern if you're "idling", but if the player is next to you you'll try to track him down however you can.

**Comment by BryanGraeser** [comment]
Oh I agree 100% from the enemy's perspective, but from a gameplay/"fun" perspective would it be better to give the player this option for escape? Especially considering flares are limited. Also perhaps these enemies are just kinda dumb (like oooh shiny flare) and there are smarter enemies that ignore flares?

**Comment by ronnie-dumesh** [comment]
Hmmm, I see what you're saying. Could be worth testing out. I can make a branch and try it out once we free up a bit.
