### ISSUE TITLE
Patrolling enemy does not move back to path after flare disappears

### ISSUE THREAD

**Issue by lsizemore8** [BryanGraeser/fallen-flame#93]
Here's what I've noticed. 
1. Flare is thrown, enemy sees it
2. Flare goes out **before the enemy reaches it**, but enemy still goes to flare
3. Enemy reaches flare position and remains there, regardless if the player's light radius hits enemy. 

If the flare is lit and the player's light radius reaches the enemy, the enemy will go to the flare, however, once the flare is out, there are issues

**Comment by BryanGraeser** [comment]
solved
