### ISSUE TITLE
Exit level to level select

### ISSUE THREAD

**Issue by BryanGraeser** [BryanGraeser/fallen-flame#98]
Introduced by PR #97 

Current issues:
- Sounds keep playing. For some reason, unable to stop enemy sounds, other models don't have a way to get active sounds. This needs to be fixed, but may not be an issue for the presentation.
- I had to create 2 GameCanvas's in gdxRoot: one for GameEngine and one for LevelSelectMode. This is because Engine does things to the GameCanvas that I am having trouble reverting (such as moving the camera and changing font colors etc).

**Comment by foxhatleo** [comment]
Resolved in #118
